
import type { Product } from './types';

// This is now just the initial seed data.
// The app will use localStorage as the primary source of truth.
export const products: Product[] = [
  {
    id: 'pringles-cheesy-cheese-1',
    name: 'Pringles Snacks Cheesy Cheese — 165g',
    price: 945,
    image: 'https://www.shopatshams.com/cdn/shop/products/PringlesSnacksCheesyCheese-165g.jpg?v=1658498424',
    imageHint: 'pringles cheesy cheese',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'pringles-hot-spicy-2',
    name: 'Pringles Snacks Hot & Spicy — 165g',
    price: 945,
    image: 'https://www.shopatshams.com/cdn/shop/products/PringlesSnacksHot_Spicy-165g.jpg?v=1658498471',
    imageHint: 'pringles hot spicy',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'pringles-original-3',
    name: 'Pringles Snacks Original — 165g',
    price: 945,
    image: 'https://www.shopatshams.com/cdn/shop/products/PringlesSnacksOriginal-165g.jpg?v=1658498528',
    imageHint: 'pringles original',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'pringles-paprika-4',
    name: 'Pringles Snacks Paprika — 165g',
    price: 945,
    image: 'https://www.shopatshams.com/cdn/shop/products/PringlesSnacksPaprika-165g.jpg?v=1658498565',
    imageHint: 'pringles paprika',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'pringles-sour-cream-onion-5',
    name: 'Pringles Snacks Sour Cream & Onion — 165g',
    price: 945,
    image: 'https://www.shopatshams.com/cdn/shop/products/PringlesSnacksSourCream_Onion-165g.jpg?v=1658498616',
    imageHint: 'pringles sour cream',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'kurkure-naughty-tomato-6',
    name: 'Kurkure Naughty Tomato — 47.5g',
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/KurkureNaughtyTomato-47.5g.jpg?v=1658494951',
    imageHint: 'kurkure tomato',
    category: 'Snacks',
  },
  {
    id: 'kurkure-masala-munch-7',
    name: 'Kurkure Masala Munch — 47.5g',
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/KurkureMasalaMunch-47.5g.jpg?v=1658494879',
    imageHint: 'kurkure masala',
    category: 'Snacks',
  },
  {
    id: 'kurkure-chutney-chaska-8',
    name: 'Kurkure Chutney Chaska — 47.5g',
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/KurkureChutneyChaska-47.5g.jpg?v=1658494794',
    imageHint: 'kurkure chutney',
    category: 'Snacks',
  },
  {
    id: 'kurkure-chilli-chatka-9',
    name: 'Kurkure Chilli Chatka — 47.5g',
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/KurkureChilliChatka-47.5g.jpg?v=1658494711',
    imageHint: 'kurkure chilli',
    category: 'Snacks',
  },
  {
    id: 'lays-flamin-hot-10',
    name: "Lays Flamin' Hot — 34.5g",
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/LaysFlamin_Hot-34.5g.jpg?v=1658495475',
    imageHint: 'lays flamin hot',
    category: 'Snacks',
  },
  {
    id: 'lays-french-cheese-11',
    name: 'Lays French Cheese — 34.5g',
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/LaysFrenchCheese-34.5g.jpg?v=1658495576',
    imageHint: 'lays french cheese',
    category: 'Snacks',
  },
  {
    id: 'lays-classic-salted-12',
    name: 'Lays Classic Salted — 34.5g',
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/LaysClassicSalted-34.5g.jpg?v=1658495393',
    imageHint: 'lays classic',
    category: 'Snacks',
  },
  {
    id: 'lays-yogurt-herb-13',
    name: 'Lays Yogurt & Herb — 34.5g',
    price: 75,
    image: 'https://www.shopatshams.com/cdn/shop/products/LaysYogurt_Herb-34.5g.jpg?v=1658495679',
    imageHint: 'lays yogurt herb',
    category: 'Snacks',
  },
  {
    id: 'slanty-cheese-flavor-14',
    name: 'Slanty Cheese Flavor — 20g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SlantyCheeseFlavor-20g.jpg?v=1658498877',
    imageHint: 'slanty cheese',
    category: 'Snacks',
  },
  {
    id: 'slanty-chilli-flavor-15',
    name: 'Slanty Chilli Flavor — 20g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SlantyChilliFlavor-20g.jpg?v=1658498932',
    imageHint: 'slanty chilli',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-salad-16',
    name: 'Super Crisp Salad (Salted) — 22g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SuperCrispSalad_Salted_-22g.jpg?v=1658499719',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-masala-masti-17',
    name: 'Super Crisp Masala Masti — 22g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SuperCrispMasalaMasti-22g.jpg?v=1658499427',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-pizza-18',
    name: 'Super Crisp Pizza — 22g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SuperCrispPizza-22g.jpg?v=1658499540',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-bbq-19',
    name: 'Super Crisp BBQ — 22g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SuperCrispBBQ-22g.jpg?v=1658499256',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-ketchup-20',
    name: 'Super Crisp Ketchup — 22g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SuperCrispKetchup-22g.jpg?v=1658499343',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-sour-cream-onion-21',
    name: 'Super Crisp Sour Cream & Onion — 22g',
    price: 35,
    image: 'https://www.shopatshams.com/cdn/shop/products/SuperCrispSourCream_Onion-22g.jpg?v=1658499808',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'wavy-maxx-sizzling-bbq-22',
    name: 'Wavy Maxx Sizzling BBQ — 25g',
    price: 50,
    image: 'https://www.shopatshams.com/cdn/shop/products/WavyMaxxSizzlingBBQ-25g.jpg?v=1658500204',
    imageHint: 'wavy maxx',
    category: 'Snacks',
  },
  {
    id: 'wavy-maxx-creamy-onion-23',
    name: 'Wavy Maxx Creamy Onion — 25g',
    price: 50,
    image: 'https://www.shopatshams.com/cdn/shop/products/WavyMaxxCreamyOnion-25g.jpg?v=1658500140',
    imageHint: 'wavy maxx',
    category: 'Snacks',
  },
  {
    id: 'biscolata-mood-chocolate-24',
    name: 'Biscolata Mood Chocolate — 100g',
    price: 399,
    image: 'https://www.shopatshams.com/cdn/shop/products/BiscolataMoodChocolate-100g.jpg?v=1658490714',
    imageHint: 'biscolata chocolate',
    category: 'Biscuits',
  },
  {
    id: 'tuc-biscuit-25',
    name: 'Tuc Biscuit — 66g',
    price: 80,
    image: 'https://www.shopatshams.com/cdn/shop/products/TucBiscuit-66g.jpg?v=1658499946',
    imageHint: 'tuc biscuit',
    category: 'Biscuits',
  },
  {
    id: 'prince-biscuit-26',
    name: 'Prince Biscuit — 68g',
    price: 80,
    image: 'https://www.shopatshams.com/cdn/shop/products/PrinceBiscuit-68g.jpg?v=1658498670',
    imageHint: 'prince biscuit',
    category: 'Biscuits',
  },
];

export const bestSellers: Product[] = [];
