
import type { Product } from './types';

// This is now just the initial seed data.
// The app will use localStorage as the primary source of truth.
export const products: Product[] = [
  {
    id: 'ritter-sport-marzipan-1',
    name: 'Ritter Sport Marzipan Dark Chocolate, Fresh from Germany, Chocolate with Marzipan Filling, Ritter Sport Chocolates in Colorful Variety, 3.5 Ounce (Pack of 12)',
    price: 945,
    image: 'https://iili.io/fYK3fZN.jpg',
    imageHint: 'ritter sport marzipan chocolate',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'ritter-sport-kakao-mousse-2',
    name: 'Ritter Sport Kakao (Cocoa) Mousse Chocolate - Pack of 3',
    price: 945,
    image: 'https://iili.io/fYKB46B.png',
    imageHint: 'ritter sport kakao mousse chocolate',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'ritter-sport-milk-chocolate-3',
    name: 'Ritter Sport Milk Chocolate with Butter Biscuit, 3.5 oz',
    price: 945,
    image: 'https://iili.io/fYfKy0P.png',
    imageHint: 'ritter sport milk chocolate butter biscuit',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'mogu-mogu-pineapple-4',
    name: 'Mogu Mogu Juice with Nata De Coco, Pineapple',
    price: 350,
    image: 'https://iili.io/fYfjJVa.png',
    imageHint: 'mogu mogu juice pineapple nata de coco',
    category: 'Drinkable',
    isNew: true,
  },
  {
    id: 'pringles-cheesy-cheese-5',
    name: 'Pringles Cheesy Cheese Chips 165g',
    price: 945,
    image: 'https://iili.io/fYqlfxR.png',
    imageHint: 'pringles cheesy cheese chips',
    category: 'Eatables',
    isNew: true,
  },
  {
    id: 'kurkure-naughty-tomato-6',
    name: 'Kurkure Naughty Tomato — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-naughty-tomato/600/600',
    imageHint: 'kurkure tomato',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'kurkure-masala-munch-7',
    name: 'Kurkure Masala Munch — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-masala-munch/600/600',
    imageHint: 'kurkure masala',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'kurkure-chutney-chaska-8',
    name: 'Kurkure Chutney Chaska — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-chutney-chaska/600/600',
    imageHint: 'kurkure chutney',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'kurkure-chilli-chatka-9',
    name: 'Kurkure Chilli Chatka — 47.5g',
    price: 75,
    image: 'https://picsum.photos/seed/kurkure-chilli-chatka/600/600',
    imageHint: 'kurkure chilli',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'lays-flamin-hot-10',
    name: "Lays Flamin' Hot — 34.5g",
    price: 75,
    image: 'https://picsum.photos/seed/lays-flamin-hot/600/600',
    imageHint: 'lays flamin hot',
    category: 'Snacks',
    isNew: true,
  },
  {
    id: 'lays-french-cheese-11',
    name: 'Lays French Cheese — 34.5g',
    price: 75,
    image: 'https://picsum.photos/seed/lays-french-cheese/600/600',
    imageHint: 'lays french cheese',
    category: 'Snacks',
  },
  {
    id: 'lays-classic-salted-12',
    name: 'Lays Classic Salted — 34.5g',
    price: 75,
    image: 'https://picsum.photos/seed/lays-classic-salted/600/600',
    imageHint: 'lays classic',
    category: 'Snacks',
  },
  {
    id: 'lays-yogurt-herb-13',
    name: 'Lays Yogurt & Herb — 34.5g',
    price: 75,
    image: 'https://picsum.photos/seed/lays-yogurt-herb/600/600',
    imageHint: 'lays yogurt herb',
    category: 'Snacks',
  },
  {
    id: 'slanty-cheese-flavor-14',
    name: 'Slanty Cheese Flavor — 20g',
    price: 35,
    image: 'https://picsum.photos/seed/slanty-cheese-flavor/600/600',
    imageHint: 'slanty cheese',
    category: 'Snacks',
  },
  {
    id: 'slanty-chilli-flavor-15',
    name: 'Slanty Chilli Flavor — 20g',
    price: 35,
    image: 'https://picsum.photos/seed/slanty-chilli-flavor/600/600',
    imageHint: 'slanty chilli',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-salad-16',
    name: 'Super Crisp Salad (Salted) — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-salad/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-masala-masti-17',
    name: 'Super Crisp Masala Masti — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-masala-masti/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-pizza-18',
    name: 'Super Crisp Pizza — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-pizza/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-bbq-19',
    name: 'Super Crisp BBQ — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-bbq/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-ketchup-20',
    name: 'Super Crisp Ketchup — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-ketchup/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'super-crisp-sour-cream-onion-21',
    name: 'Super Crisp Sour Cream & Onion — 22g',
    price: 35,
    image: 'https://picsum.photos/seed/super-crisp-sour-cream-onion/600/600',
    imageHint: 'super crisp',
    category: 'Snacks',
  },
  {
    id: 'wavy-maxx-sizzling-bbq-22',
    name: 'Wavy Maxx Sizzling BBQ — 25g',
    price: 50,
    image: 'https://picsum.photos/seed/wavy-maxx-sizzling-bbq/600/600',
    imageHint: 'wavy maxx',
    category: 'Snacks',
  },
  {
    id: 'wavy-maxx-creamy-onion-23',
    name: 'Wavy Maxx Creamy Onion — 25g',
    price: 50,
    image: 'https://picsum.photos/seed/wavy-maxx-creamy-onion/600/600',
    imageHint: 'wavy maxx',
    category: 'Snacks',
  },
  {
    id: 'biscolata-mood-chocolate-24',
    name: 'Biscolata Mood Chocolate — 100g',
    price: 399,
    image: 'https://picsum.photos/seed/biscolata-mood-chocolate/600/600',
    imageHint: 'biscolata chocolate',
    category: 'Biscuits',
  },
  {
    id: 'tuc-biscuit-25',
    name: 'Tuc Biscuit — 66g',
    price: 80,
    image: 'https://picsum.photos/seed/tuc-biscuit/600/600',
    imageHint: 'tuc biscuit',
    category: 'Biscuits',
  },
  {
    id: 'prince-biscuit-26',
    name: 'Prince Biscuit — 68g',
    price: 80,
    image: 'https://picsum.photos/seed/prince-biscuit/600/600',
    imageHint: 'prince biscuit',
    category: 'Biscuits',
  },
  {
    id: 'nido-milk-powder-27',
    name: 'Nido Full Cream Milk Powder — 400g',
    price: 450,
    image: 'https://picsum.photos/seed/nido-milk-powder/600/600',
    imageHint: 'nido milk powder',
    category: 'Dairy',
  },
  {
    id: 'coca-cola-30',
    name: 'Coca Cola — 2.25L',
    price: 180,
    image: 'https://picsum.photos/seed/coca-cola/600/600',
    imageHint: 'coca cola',
    category: 'Drinkable',
  },
  {
    id: 'dove-soap-31',
    name: 'Dove Beauty Bar Soap — 100g',
    price: 120,
    image: 'https://picsum.photos/seed/dove-soap/600/600',
    imageHint: 'dove soap',
    category: 'Personal Care',
  },
  {
    id: 'detergent-powder-32',
    name: 'Ariel Detergent Powder — 1kg',
    price: 450,
    image: 'https://picsum.photos/seed/ariel-detergent/600/600',
    imageHint: 'ariel detergent',
    category: 'Household',
  },
  {
    id: 'baby-diapers-33',
    name: 'Pampers Baby Diapers — Medium (56 count)',
    price: 1200,
    image: 'https://picsum.photos/seed/pampers-diapers/600/600',
    imageHint: 'pampers diapers',
    category: 'Baby Care',
  },
];

export const bestSellers: Product[] = [];
