import React from 'react';
import { ProductDetailClient } from './product-detail-client';

export const dynamic = 'force-static';

export async function generateStaticParams() {
  // Return all product IDs that should be statically generated
  return [
    { id: 'pringles-cheesy-cheese-new-1' },
    { id: 'pringles-hot-spicy-new-2' },
    { id: 'pringles-original-new-3' },
    { id: 'pringles-paprika-new-4' },
    { id: 'pringles-sour-cream-onion-new-5' },
    { id: 'fox-fruit-tin-6' },
    { id: 'fox-berries-tin-7' },
    { id: 'fox-fruity-mints-8' },
    { id: 'lotus-biscuit-9' },
    { id: 'lotus-biscuit-spread-10' },
    { id: 'davidoff-rich-aroma-11' },
    { id: 'davidoff-fine-aroma-12' },
    { id: 'davidoff-espresso-57-13' },
    { id: 'davidoff-crema-intense-14' },
    { id: 'uncle-barns-tempura-flour-15' },
    { id: 'uncle-barns-bread-crumbs-16' },
    { id: 'nescafe-gold-decaf-17' },
    { id: 'nescafe-gold-alta-rica-18' },
    { id: 'nescafe-gold-blend-19' },
    { id: 'ritz-cracker-original-20' },
    { id: 'samyang-buldak-carbonara-21' },
    { id: 'samyang-buldak-harbenoro-lime-22' },
    { id: 'samyang-buldak-carbonara-spicy-23' },
    { id: 'samyang-buldak-2x-red-24' },
    { id: 'samyang-buldak-cheese-25' },
    { id: 'samyang-buldak-original-black-26' },
    { id: 'bounty-chocolate-bar-27' },
    { id: 'bounty-fruit-nut-bar-28' },
    { id: 'cadbury-dairy-fruit-nut-29' },
    { id: 'cadbury-dairy-hazelnut-30' },
    { id: 'cadbury-dairy-milk-31' },
    { id: 'cadbury-dairy-milk-fruit-nut-32' },
    { id: 'cadbury-dairy-milk-hazelnut-33' },
    { id: 'cadbury-dairy-milk-plain-34' },
    { id: 'cadbury-dairy-milk-roasted-almond-35' },
    { id: 'cadbury-flake-36' },
    { id: 'cadbury-flake-milk-37' },
    { id: 'ferrero-rocher-hazel-dark-38' },
    { id: 'ferrero-rocher-hazelnut-white-39' },
    { id: 'ferrero-rocher-original-milk-40' },
    { id: 'godiva-masterpieces-dark-41' },
    { id: 'godiva-masterpieces-milk-42' },
    { id: 'hershey-kisses-milk-43' },
    { id: 'kinder-joy-egg-girl-44' },
    { id: 'kinder-joy-egg-boy-45' },
    { id: 'kinder-maxi-t10-46' },
    { id: 'kinder-tronky-t5-47' },
    { id: 'kit-kat-2-finger-48' },
    { id: 'kit-kat-4-finger-uk-49' },
    { id: 'kitkat-2f-caramel-50' },
    { id: 'kitkat-2f-cookies-cream-51' },
    { id: 'kitkat-2f-dark-52' },
    { id: 'kitkat-2f-white-53' },
    { id: 'kitkat-2f-nescafe-mocha-54' },
    { id: 'mm-chocolate-pouch-55' },
    { id: 'mm-minis-pouch-56' },
    { id: 'mm-chocolate-box-57' },
    { id: 'mm-peanut-pouch-58' },
    { id: 'mackintosh-quality-street-tin-59' },
    { id: 'mackintosh-quality-street-250-60' },
    { id: 'quality-street-tin-61' },
    { id: 'malteaser-chocolate-pouch-62' },
    { id: 'celebration-tub-63' },
    { id: 'mars-fruit-nut-64' },
    { id: 'mars-regular-65' },
    { id: 'mr-beast-chocolate-almond-66' },
    { id: 'nutella-b-ready-t10-67' },
    { id: 'nutella-b-ready-t6-68' },
    { id: 'mogu-mogu-mango-69' },
    { id: 'mogu-mogu-coconut-70' },
    { id: 'mogu-mogu-pineapple-71' },
    { id: 'mogu-mogu-lychee-72' },
    { id: 'mogu-mogu-strawberry-73' },
    { id: 'mogu-mogu-peach-74' },
    { id: 'mogu-mogu-grape-75' },
    { id: 'mogu-mogu-orange-76' },
    { id: 'movenpick-decaff-77' },
    { id: 'movenpick-intense-78' },
    { id: 'movenpick-original-79' },
    { id: 'nescafe-classic-imported-80' },
    { id: 'nescafe-3in1-81' },
    { id: 'nutella-chocolate-spread-82' },
    { id: 'american-garden-peanut-chunk-83' },
    { id: 'american-garden-peanut-creamy-84' },
    { id: 'ritter-sport-cocoa-mousse-85' },
    { id: 'ritter-sport-alpine-milk-86' },
    { id: 'ritter-sport-butter-biscuit-87' },
    { id: 'ritter-sport-cashew-88' },
    { id: 'ritter-sport-cocoa-wafer-89' },
    { id: 'ritter-sport-coffee-hazelnut-90' },
    { id: 'ritter-sport-dark-almond-91' },
    { id: 'ritter-sport-dark-mint-92' },
    { id: 'ritter-sport-cornflakes-93' },
    { id: 'ritter-sport-fine-milk-94' },
    { id: 'ritter-sport-honey-salted-almond-95' },
    { id: 'ritter-sport-marzipan-96' },
    { id: 'ritter-sport-praline-94' },
    { id: 'ritter-sport-pure-50-95' },
    { id: 'ritter-sport-raisin-nut-96' },
    { id: 'ritter-sport-salted-caramel-97' },
    { id: 'ritter-sport-white-crisp-98' },
    { id: 'ritter-sport-white-hazelnut-99' },
    { id: 'ritter-sport-whole-hazelnut-100' },
    { id: 'my-chew-blueberry-101' },
    { id: 'my-chew-chocolate-102' },
    { id: 'my-chew-coconut-103' },
    { id: 'my-chew-grape-104' },
    { id: 'my-chew-lychee-105' },
    { id: 'my-chew-mango-106' },
    { id: 'my-chew-strawberry-107' },
  ];
}

export default function ProductPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = React.use(params);
  
  return (
    <ProductDetailClient productId={resolvedParams.id} />
  );
}